import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          '"Segoe UI"',
          '"Aptos"',
          '"Helvetica Neue"',
          '"Roboto"',
          '"Open Sans"',
          '"Arial"',
          'sans-serif',
        ],
        enterprise: [
          '"Segoe UI"',
          '"Aptos"',
          '"Helvetica Neue"',
          '"Roboto"',
          '"Open Sans"',
          '"Arial"',
          'sans-serif',
        ],
        mono: ['"Cascadia Code"', '"Consolas"', '"Courier New"', 'monospace'],
      },
      fontSize: {
        'page-title': ['32px', { lineHeight: '1.25', letterSpacing: '-0.5px' }],
        'section-title': ['24px', { lineHeight: '1.3' }],
        'card-title': ['18px', { lineHeight: '1.4' }],
        'modal-title': ['22px', { lineHeight: '1.3' }],
        'body-normal': ['14px', { lineHeight: '1.6' }],
        'btn-text': ['14px', { lineHeight: '1.4', letterSpacing: '0.2px' }],
        'nav-text': ['15px', { lineHeight: '1.4' }],
        'sidebar-text': ['14px', { lineHeight: '1.5' }],
        'th-text': ['13px', { lineHeight: '1.4', letterSpacing: '0.3px' }],
        'td-text': ['13px', { lineHeight: '1.5' }],
        'label-text': ['14px', { lineHeight: '1.4' }],
        'input-text': ['14px', { lineHeight: '1.4' }],
        'badge-text': ['12px', { lineHeight: '1.3' }],
        'tooltip-text': ['12px', { lineHeight: '1.3' }],
      },
      fontWeight: {
        'page-title': '700',
        'section-title': '600',
        'card-title': '600',
        'modal-title': '700',
        'btn-weight': '600',
        'nav-weight': '600',
        'sidebar-weight': '500',
        'th-weight': '600',
        'label-weight': '500',
        'badge-weight': '600',
      },
      colors: {
        "bg-main": "var(--bg-main)",
        "bg-panel": "var(--bg-panel)",
        "border-default": "var(--border-default)",
        "accent-green": "var(--accent-green)",
        "accent-red": "var(--accent-red)",
        "accent-blue": "var(--accent-blue)",
        "accent-cyan": "var(--accent-cyan)",
        "accent-yellow": "var(--accent-yellow)",
        "page-title": "var(--text-primary)",
        "section-title": "var(--text-primary)",
        "body-text": "var(--text-muted)",
        "table-data": "var(--text-primary)",
        "placeholder-text": "var(--text-muted)",
      },
    },
  },
  plugins: [],
};
export default config;
