# Helper functions to simulate cloud API outputs locally
def mock_azure_ocr_call(file_content: bytes) -> str:
    # Simulates text extracted from a PDF invoice layout
    return """
    INVOICE #99827
    Vendor: ACME Corporation
    Date: 2026-06-28
    Subtotal: 150.00
    Tax: 15.00
    Grand Total: 165.00
    """

def mock_llm_extraction_call(ocr_text: str) -> dict:
    # Simulates structured JSON generated by Azure OpenAI models
    return {
        "vendor_name": "ACME Corporation",
        "subtotal": 150.00,
        "tax_amount": 15.00,
        "grand_total": 165.00
    }