import React from "react";
import { HelpSection } from "./trainer-guide";

function P({ children }: { children: React.ReactNode }) {
  return <p className="text-sm text-slate-300 leading-relaxed">{children}</p>;
}

export const OUTBOUND_EMAIL_HELP_SECTIONS: HelpSection[] = [
  {
    id: "outbound-email-overview",
    title: "Outbound Invoice Delivery Guide",
    keywords: ["outbound", "email", "delivery", "dispatch", "customer", "invoice send"],
    searchText: "outbound email delivery dispatch customer invoice send billing target address",
    body: (
      <>
        <P>
          The <strong>Outbound Invoice Delivery</strong> configuration specifies where customer invoices generated by your business are dispatched.
        </P>

        <div className="space-y-2 mt-3">
          <h4 className="text-xs font-semibold text-white uppercase tracking-wider">Outbound Dispatch Setup</h4>
          <ol className="space-y-1.5 text-xs text-slate-300 list-decimal pl-5">
            <li>Navigate to <strong>Settings → Email</strong>.</li>
            <li>Configure your <strong>Target Email Address(es)</strong> (e.g. <code className="text-blue-300">billing@company.com, ap@company.com</code>).</li>
            <li>In the <strong>Outbound Review Console</strong>, clicking <strong>Approve & Send</strong> validates line items and dispatches formal invoice notifications to configured recipient addresses.</li>
          </ol>
        </div>
      </>
    ),
  },
];
