"""Initial schema

Revision ID: 18c8f79cfbd0
Revises: c6e338d84981
Create Date: 2026-07-14 15:22:03.123925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18c8f79cfbd0'
down_revision: Union[str, Sequence[str], None] = 'c6e338d84981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('clerk_user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('audit_logs', 'actor_user_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.create_foreign_key(None, 'audit_logs', 'users', ['actor_user_id'], ['id'])
    op.add_column('invoice', sa.Column('coordinates', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('invoice', sa.Column('field_confidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('invoice', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('invoice', sa.Column('discount_percent', sa.Float(), nullable=True))
    op.add_column('invoice', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.add_column('invoice', sa.Column('taxes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('invoice', sa.Column('discounts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('invoice', sa.Column('deductions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('invoice', sa.Column('tax_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('invoice', sa.Column('payment_instructions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('invoice', sa.Column('references', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('invoice', sa.Column('addresses', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('invoice', sa.Column('compliance_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'compliance_metadata')
    op.drop_column('invoice', 'addresses')
    op.drop_column('invoice', 'references')
    op.drop_column('invoice', 'payment_instructions')
    op.drop_column('invoice', 'tax_ids')
    op.drop_column('invoice', 'deductions')
    op.drop_column('invoice', 'discounts')
    op.drop_column('invoice', 'taxes')
    op.drop_column('invoice', 'discount_amount')
    op.drop_column('invoice', 'discount_percent')
    op.drop_column('invoice', 'currency')
    op.drop_column('invoice', 'field_confidence')
    op.drop_column('invoice', 'coordinates')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.alter_column('audit_logs', 'actor_user_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
