"""add_file_hash_column

Revision ID: c6e338d84981
Revises: d0246352d051
Create Date: 2026-07-01 11:29:36.036806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c6e338d84981'
down_revision: Union[str, Sequence[str], None] = 'd0246352d051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('file_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.create_index(op.f('ix_invoice_file_hash'), 'invoice', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_file_hash'), table_name='invoice')
    op.drop_column('invoice', 'file_hash')
    # ### end Alembic commands ###
