"""create_missing_tables

Revision ID: d0246352d051
Revises: 186a46f1f222
Create Date: 2026-07-01 09:21:02.261959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0246352d051'
down_revision: Union[str, Sequence[str], None] = '186a46f1f222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('actor_role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_invoice_id'), 'audit_logs', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('chatmessage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generated_sql', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('citations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatmessage_session_id'), 'chatmessage', ['session_id'], unique=False)
    op.create_table('chatsession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatsession_tenant_id'), 'chatsession', ['tenant_id'], unique=False)
    op.create_table('extraction_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_templates_tenant_id'), 'extraction_templates', ['tenant_id'], unique=False)
    op.create_table('tenant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('billing_plan', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('free_invoices_remaining', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_domain'), 'tenant', ['domain'], unique=True)
    op.add_column('invoice', sa.Column('batch_id', sa.Uuid(), nullable=True))
    op.add_column('invoice', sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False))
    op.add_column('invoice', sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('invoice', sa.Column('invoice_date', sa.Date(), nullable=True))
    op.add_column('invoice', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('invoice', sa.Column('tax_amount', sa.Float(), nullable=True))
    op.add_column('invoice', sa.Column('po_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('invoice', sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('invoice', sa.Column('items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.create_index(op.f('ix_invoice_batch_id'), 'invoice', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_batch_id'), table_name='invoice')
    op.drop_column('invoice', 'items')
    op.drop_column('invoice', 'tags')
    op.drop_column('invoice', 'po_number')
    op.drop_column('invoice', 'tax_amount')
    op.drop_column('invoice', 'due_date')
    op.drop_column('invoice', 'invoice_date')
    op.drop_column('invoice', 'invoice_number')
    op.drop_column('invoice', 'file_path')
    op.drop_column('invoice', 'batch_id')
    op.drop_index(op.f('ix_tenant_domain'), table_name='tenant')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_extraction_templates_tenant_id'), table_name='extraction_templates')
    op.drop_table('extraction_templates')
    op.drop_index(op.f('ix_chatsession_tenant_id'), table_name='chatsession')
    op.drop_table('chatsession')
    op.drop_index(op.f('ix_chatmessage_session_id'), table_name='chatmessage')
    op.drop_table('chatmessage')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_invoice_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
