"""add_subtotal_to_invoice

Revision ID: 46b051e6b0a0
Revises: f18a0c4b7d21
Create Date: 2026-08-17 13:36:12.733807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46b051e6b0a0'
down_revision: Union[str, None] = 'f18a0c4b7d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('subtotal', sa.Float(), nullable=True))
    op.alter_column('webhook_subscriptions', 'event_failure_counts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhook_subscriptions', 'event_failure_counts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('invoice', 'subtotal')
    # ### end Alembic commands ###
