"""add support ticket table

Revision ID: 6c60f6e907a0
Revises: 46b051e6b0a0
Create Date: 2026-08-17 15:53:10.497235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c60f6e907a0'
down_revision: Union[str, None] = '46b051e6b0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supportticket',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_number', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('chat_transcript', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('admin_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supportticket_tenant_id'), 'supportticket', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_supportticket_ticket_number'), 'supportticket', ['ticket_number'], unique=True)
    op.create_index(op.f('ix_supportticket_user_email'), 'supportticket', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supportticket_user_email'), table_name='supportticket')
    op.drop_index(op.f('ix_supportticket_ticket_number'), table_name='supportticket')
    op.drop_index(op.f('ix_supportticket_tenant_id'), table_name='supportticket')
    op.drop_table('supportticket')
    # ### end Alembic commands ###
