"""AddTenantEmailSenders

Revision ID: 71d18e2c3349
Revises: 72f453814de1
Create Date: 2026-07-28 10:26:31.506801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '71d18e2c3349'
down_revision: Union[str, None] = '72f453814de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_email_senders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_tenant_email_senders_tenant_email')
    )
    op.create_index(op.f('ix_tenant_email_senders_email'), 'tenant_email_senders', ['email'], unique=False)
    op.create_index(op.f('ix_tenant_email_senders_tenant_id'), 'tenant_email_senders', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('chat_feedback_message_id_key'), 'chat_feedback', type_='unique')
    op.drop_index(op.f('ix_chat_feedback_message_id'), table_name='chat_feedback')
    op.create_index(op.f('ix_chat_feedback_message_id'), 'chat_feedback', ['message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_feedback_message_id'), table_name='chat_feedback')
    op.create_index(op.f('ix_chat_feedback_message_id'), 'chat_feedback', ['message_id'], unique=False)
    op.create_unique_constraint(op.f('chat_feedback_message_id_key'), 'chat_feedback', ['message_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_tenant_email_senders_tenant_id'), table_name='tenant_email_senders')
    op.drop_index(op.f('ix_tenant_email_senders_email'), table_name='tenant_email_senders')
    op.drop_table('tenant_email_senders')
    # ### end Alembic commands ###
