"""add_autopilot_tables

Revision ID: 857ef0378718
Revises: f9a0b1c2d3e4
Create Date: 2026-08-12 16:51:20.333842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '857ef0378718'
down_revision: Union[str, None] = 'f9a0b1c2d3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_autopilot_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('flow_direction', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('trigger_mode', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('trigger_value', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('notify_emails', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('send_approval_links', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_autopilot_config_tenant')
    )
    op.create_index('idx_autopilot_config_tenant', 'tenant_autopilot_configs', ['tenant_id'], unique=False)
    op.create_table('tenant_autopilot_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('error_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_autopilot_log_hash', 'tenant_autopilot_logs', ['content_hash'], unique=False)
    op.create_index('idx_autopilot_log_tenant_file', 'tenant_autopilot_logs', ['tenant_id', 'source_file_id'], unique=False)
    op.create_index(op.f('ix_tenant_autopilot_logs_tenant_id'), 'tenant_autopilot_logs', ['tenant_id'], unique=False)
    op.alter_column('webhook_subscriptions', 'subscribed_events',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhook_subscriptions', 'subscribed_events',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_tenant_autopilot_logs_tenant_id'), table_name='tenant_autopilot_logs')
    op.drop_index('idx_autopilot_log_tenant_file', table_name='tenant_autopilot_logs')
    op.drop_index('idx_autopilot_log_hash', table_name='tenant_autopilot_logs')
    op.drop_table('tenant_autopilot_logs')
    op.drop_index('idx_autopilot_config_tenant', table_name='tenant_autopilot_configs')
    op.drop_table('tenant_autopilot_configs')
    # ### end Alembic commands ###
